/**
 * The README, the docs and the talk pages point into the source by line range ("here is the WHEN,
 * here the HOW, here the WHAT"). Line ranges rot silently when a file is edited, so this test pins
 * them: every relative link must resolve, a `#Lx-Ly` range must lie inside the file, every
 * backticked name in the link text (`WHEN TO USE`, `computeBuildingDerived`, …) must appear inside
 * that range, and a `#heading` anchor into a Markdown file must match one of its headings.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
// docs/wire/ is generated by `npm run wire-view` and holds no links.
const DOCS = [
  'README.md',
  ...readdirSync(join(ROOT, 'docs'))
    .filter((f) => f.endsWith('.md'))
    .map((f) => `docs/${f}`),
  ...readdirSync(join(ROOT, 'talks'))
    .filter((f) => f.endsWith('.md'))
    .map((f) => `talks/${f}`),
];

const links = DOCS.flatMap((doc) =>
  [...readFileSync(join(ROOT, doc), 'utf8').matchAll(/\[((?:[^\[\]]|`[^`]*`)+)\]\(([^)\s]+)\)/g)]
    .map((m) => ({ doc, text: m[1], target: m[2] }))
    .filter((l) => !/^(https?:|mailto:)/.test(l.target))
    .map((l) => {
      const [path, anchor] = l.target.split('#');
      const file = path ? resolve(ROOT, dirname(l.doc), decodeURIComponent(path)) : join(ROOT, l.doc);
      return { ...l, file, anchor, label: `${l.doc} → ${l.target}` };
    }),
);

/** GitHub's heading slug: lowercase, drop punctuation except `-` and `_`, spaces to `-`. */
const slug = (heading: string) =>
  heading
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .replace(/\s/g, '-');

const headingSlugs = (file: string) =>
  readFileSync(file, 'utf8')
    .replace(/^(```|````)[\s\S]*?^\1/gm, '')
    .split('\n')
    .filter((l) => /^#{1,6}\s/.test(l))
    .map((l) => slug(l.replace(/^#+\s/, '')));

const lineRanged = links.filter((l) => l.anchor && /^L\d+/.test(l.anchor));
const headingAnchored = links.filter((l) => l.anchor && !/^L\d+/.test(l.anchor) && l.file.endsWith('.md'));

describe('README and docs links into the repo', () => {
  it('finds the line-anchored links of the source walkthrough', () => {
    const walkthrough = lineRanged.filter((l) => l.doc === 'docs/reference-implementation.md');
    expect(walkthrough.length).toBeGreaterThanOrEqual(15);
  });

  it.each(links.map((l) => [l.label, l]))('%s resolves', (_, l) => {
    expect(existsSync(l.file), relative(ROOT, l.file)).toBe(true);
  });

  it.each(lineRanged.map((l) => [l.label, l]))('%s covers what its text names', (_, l) => {
    const [, from, to] = l.anchor.match(/^L(\d+)(?:-L(\d+))?$/)!;
    const lines = readFileSync(l.file, 'utf8').split('\n');
    const a = Number(from),
      b = Number(to ?? from);
    expect(a).toBeLessThanOrEqual(b);
    expect(b, `${l.target} runs past the end of the file`).toBeLessThanOrEqual(lines.length);
    expect(lines[a - 1].trim(), `${l.target} starts on a blank line`).not.toBe('');
    const range = lines.slice(a - 1, b).join('\n');
    for (const [, name] of l.text.matchAll(/`([^`]+)`/g)) {
      if (/\.(ts|md|json)$/.test(name)) continue;
      expect(range, `${l.target} should contain ${name}`).toContain(name);
    }
  });

  it.each(headingAnchored.map((l) => [l.label, l]))('%s hits a heading', (_, l) => {
    expect(headingSlugs(l.file)).toContain(l.anchor);
  });
});
