/**
 * What a tier actually sends to the model, as readable markdown: server instructions and every
 * model-visible tool's description, with Claude Code's 2,048-char cut marked (Q7), plus the input parameters.
 * The output schema is listed by size only, because the model never receives it (Q11).
 *
 * Generated from the live server factory, never written by hand: `npm run wire-view` rewrites
 * docs/wire/, and src/wire-view.test.ts fails when a file there no longer matches.
 */
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createServer, type ServerVariant } from './server.js';
import type { BagClientLike, EpOnlineClientLike } from './tools/get-building-profile.js';

export const CUT = 2048;
export const WIRE_VIEW_ARMS: { arm: ServerVariant; blurb: string }[] = [
  {
    arm: 'best',
    blurb:
      'The reference implementation: everything before the call fits inside the cut; meaning travels in field names and the response.',
  },
  {
    arm: 'rich',
    blurb:
      'The older, description-heavy tier: most of its INTERPRETATION sits past the cut and never reaches the model on Claude Code.',
  },
  { arm: 'minimal', blurb: 'The thin wrapper: same data, one-line descriptions, no guidance.' },
];
/** App-only tools (`_meta.ui.visibility: ['app']`) are called by the UI, never shown to the model. */
const modelVisible = (t: { _meta?: unknown }) =>
  !(t._meta as { ui?: { visibility?: string[] } } | undefined)?.ui?.visibility?.every((v) => v === 'app');

const noBag: BagClientLike = {
  findAddress: async () => [],
  getVerblijfsobject: async () => null,
  getPand: async () => null,
};
const noEp: EpOnlineClientLike = { getByBagVboId: async () => [] };

const fence = (text: string) => '````text\n' + text + '\n````';

/** The text as delivered, with a visible marker where Claude Code stops sending it. */
export function markCut(text: string): string {
  if (text.length <= CUT) return fence(text);
  const lost = text.length - CUT;
  return (
    fence(text.slice(0, CUT)) +
    `\n\n> ✂ **Claude Code cuts here, at character ${CUT.toLocaleString('en')}.** ` +
    `The model never receives the ${lost.toLocaleString('en')} characters below (${Math.round((100 * lost) / text.length)}%).\n\n` +
    '<details><summary>Not delivered</summary>\n\n' +
    fence(text.slice(CUT)) +
    '\n\n</details>'
  );
}

type Prop = { type?: string; description?: string; enum?: unknown[] };

export async function renderWireView(arm: ServerVariant, blurb: string): Promise<string> {
  const server = createServer({ variant: arm, bagClient: noBag, epOnlineClient: noEp });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: 'wire-view', version: '0.0.0' });
  await Promise.all([client.connect(clientTransport), server.connect(serverTransport)]);
  const { tools } = await client.listTools();
  const instructions = client.getInstructions() ?? '';
  await client.close();

  const out: string[] = [
    `# \`${arm}\` — what the model receives`,
    '',
    `${blurb}`,
    '',
    `Generated by \`npm run wire-view\` from \`createServer({ variant: '${arm}' })\`. Do not edit by hand.`,
    '',
    `## Server instructions (${instructions.length.toLocaleString('en')} chars)`,
    '',
    instructions ? markCut(instructions) : '_none_',
  ];
  for (const tool of tools.filter(modelVisible)) {
    const name = tool.name;
    const description = tool.description ?? '';
    const props = ((tool.inputSchema as { properties?: Record<string, Prop> }).properties ?? {}) as Record<
      string,
      Prop
    >;
    const required = new Set((tool.inputSchema as { required?: string[] }).required ?? []);
    out.push(
      '',
      `## \`${name}\``,
      '',
      `### Description (${description.length.toLocaleString('en')} chars)`,
      '',
      markCut(description),
      '',
      '### Input parameters (delivered)',
      '',
      '| parameter | type | description |',
      '|---|---|---|',
      ...Object.entries(props).map(
        ([k, p]) =>
          `| \`${k}\`${required.has(k) ? ' *' : ''} | ${p.enum ? p.enum.map((v) => `\`${String(v)}\``).join(' · ') : (p.type ?? '')} | ${(p.description ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`,
      ),
      '',
      '### Output schema (not delivered)',
      '',
      tool.outputSchema
        ? `${JSON.stringify(tool.outputSchema).length.toLocaleString('en')} chars, ${Object.keys((tool.outputSchema as { properties?: object }).properties ?? {}).length} top-level fields. Claude Code does not pass it to the model (Q11), so nothing in it can carry meaning.`
        : '_none_',
    );
  }
  return out.join('\n') + '\n';
}
